version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    env_file: ./env/.mongo.env

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    env_file: ./env/.mongo-express.env

  # See https://github.com/airnotifier/airnotifier
  airnotifier:
    image: airnotifier
    depends_on:
      - mongo
    volumes:
      - ./certs:/var/airnotifier/pemdir
      - ./logs:/var/log/airnotifier
    ports:
      - 8801:8801
    env_file: ./env/.airnotifier.env

  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    depends_on:
      - mongo
    ports:
      - 4466:4466
    # todo: put PRISMA_CONFIG in .prisma.env
    # env_file: ./env/.prisma.env
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mongo
            uri: mongodb://root:example@mongo:27017

