version: '3.1'

services:

  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    depends_on:
      - mongo
    ports:
      - 4466:4466
    networks:
      - pandemic
    # todo: put PRISMA_CONFIG in .prisma.env
    # env_file: ./env/.prisma.env
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mongo
            uri: mongodb://root:example@mongo:27017


